### PR TITLE
fix(java): remove duplicate IntoJava impl for &BasePath

### PR DESCRIPTION
**Pull request by LuciferYang**
## Summary

The Java JNI build on `main` is broken since #8925 ([failing run](https://github.com/lance-format/lance/actions/runs/33884542905/job/101061005145)):

```
error[E0119]: conflicting implementations of trait `IntoJava` for type `&lance_table::format::BasePath`
   --> src/transaction.rs:125:1
    |
125 | impl IntoJava for &BasePath {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `&lance_table::format::BasePath`
    |
::: src/blocking_dataset.rs:89:1
 89 | impl IntoJava for &BasePath {
    | --------------------------- first implementation here
```

#8925 added an `impl IntoJava for &BasePath` in `transaction.rs` that duplicates the pre-existing, behaviorally identical impl in `blocking_dataset.rs`. This removes the duplicate; the `Overwrite.initial_bases` export in `transaction.rs` resolves to the impl in `blocking_dataset.rs`, and the now-unused `BasePath` import is dropped.

## Test Plan

- `cargo check --manifest-path java/lance-jni/Cargo.toml` — passes (previously E0119)
- `cargo clippy --tests --manifest-path java/lance-jni/Cargo.toml` — clean
- `cargo test --manifest-path java/lance-jni/Cargo.toml --lib` — 22 passed (incl. `transaction::tests::test_checked_transaction_integer_conversions`, which covers the `basePath.id` overflow conversion)
- Reintroducing a duplicate impl is caught by the compiler itself (E0119), so no new test is needed for the removal

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @Xuanwo To fix the CI failures on main

**Review by Xuanwo — APPROVED** [review]

**Comment by LuciferYang** [comment]
Thank you @Xuanwo
