### PR TITLE
fix(index): implement with_io_priority for FailNewFileStore test store

### PR DESCRIPTION
**Pull request by LuciferYang**
## What

The `lance-index` **test build** is currently broken on `main`: `error[E0046]: not all trait items implemented, missing: with_io_priority` at `rust/lance-index/src/scalar/fmindex.rs`.

`with_io_priority` was added to the `IndexStore` trait in #7449. The `FailNewFileStore` test fixture was added later in #7422 (which branched before #7449 landed), so it never implemented the new method. Each PR was green on its own; together on `main` the test build fails — a semantic merge conflict. It only surfaces in the `Build tests` step because the fixture is `#[cfg(test)]`.

## Fix

Implement `with_io_priority` on `FailNewFileStore` by delegating to the inner store and re-wrapping, mirroring how the fixture already delegates its other read methods while keeping the injected `new_index_file` failure.

## Verification

- `cargo check -p lance-index --tests` — compiles (was failing on `main`).
- `cargo test -p lance-index --lib fmindex` — 24 passed.
- `cargo fmt -p lance-index -- --check` and `cargo clippy -p lance-index --tests` — clean.

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @hamersaw @Xuanwo main ci failed

**Comment by LuciferYang** [comment]
also cc @jackye1995

**Review by Xuanwo — APPROVED** [review]

**Comment by LuciferYang** [comment]
Thank you @Xuanwo
