### PR TITLE
fix(table): restore migration_next_row_id on ManifestBuildConfig

### PR DESCRIPTION
**Pull request by wjones127**
`main` does not compile, which fails the Rust, Python, and Java workflows on main and on every open PR.

Two PRs that were each green on their own collided semantically. #8521 added a `migration_next_row_id` option to `ManifestWriteConfig` and read it while building the manifest. #8053 then moved that config down into `lance-table` as the new `ManifestBuildConfig`; because it branched before #8521, the new struct had no such field. Git merged both cleanly, so the break only appeared once the second one landed:

```
error[E0609]: no field `migration_next_row_id` on type `&lance_table::format::ManifestBuildConfig`
    --> rust/lance/src/dataset/transaction.rs:2230:23
```

This PR adds the missing field to `ManifestBuildConfig` and passes it through `ManifestWriteConfig::to_build_config`. The code that reads it is already correct and is unchanged.

No new test: the five `migrate_to_stable_row_ids` tests added by #8521 already cover this behavior, and they pass again now that the crate compiles.

### CODE REVIEW

**Review by xuanyu-z — APPROVED** [review]

**Comment by dentiny** [comment]
Curious is it because of merge conflict?

**Review by dentiny — APPROVED** [review]

**Review by Xuanwo — APPROVED** [review]
