### PR TITLE
fix: remove duplicate LanceFileVersion import in lance-file tests

### PR DESCRIPTION
**Pull request by wjones127**
Every Rust CI job on `main` has failed since a2d3047e4 (#8227) with a duplicate-import error:

```
error[E0252]: the name `LanceFileVersion` is defined multiple times
    --> rust/lance-file/src/reader.rs:2462:47
```

`lance-file`'s own `crate::version` module re-exports `LanceFileVersion` from `lance_encoding::version`, and the reader's test module already imported it from there alongside `ConcreteFileVersion`. #8227 added a second import of the same type directly from `lance_encoding::version`, so the test module no longer compiles. Because it is a `#[cfg(test)]` module, a plain build is unaffected and only the test-compiling jobs break — which is all of them, including clippy, where the accompanying unused-import warning is promoted to an error by `-D warnings`.

This PR drops the added import and keeps the crate-local one.

### CODE REVIEW

**Review by geruh — APPROVED** [review]

**Review by wombatu-kun — APPROVED** [review]

**Comment by wombatu-kun** [comment]
@Xuanwo could you land this? It is green with two approvals, and `main` stays red until it merges.

**Review by jackye1995 — APPROVED** [review]
